version: '3'
services:
  geth:
    build:
      context: ./geth
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - geth_data:/root/.ethereum

volumes:
  geth_data:
